unbind r
bind r source-file ~/.config/tmux/tmux.conf
#Set Prefix
set -g prefix C-s 
set -g mouse on 

#Tmux Windows Navigation
bind -n M-H previous-window
bind -n M-L next-window

#Set Windows and Panes at 1 not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1

#Set vi-mode
bind-key -T copy-mode-vi v send-keys -X beging-selection
bind-key -T copy-mode-vi C-v send keys -X rectangle-toggle
bind-key -T copy-mode-vi y send keys -X copy-selection-and-cancel


#Colors:
set -g default-terminal "screen-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set-option -sa terminal-overrides ",xterm*:Tc"
set-option -ga terminal-overrides ",xterm-256color:Tc"


#List of Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'odedlaz/tmux-onedark-theme'
set -g @tmux-onedark-theme-show-powerline true
set -g @tmux-onedark-theme-show-flags true 
set -g @tmux-onedark-theme-show-left-icon session
set -g status-position top


#Stay at bottom
run '~/.config/tmux/plugins/tpm/tpm'
