unbind r
bind r source-file ~/.config/tmux/tmux.conf

set -g prefix C-s 

setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D 
bind-key k select-pane -U  
bind-key l select-pane -R

#Colors:
set -g default-terminal "screen-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set-option -sa terminal-overrides ",xterm*:Tc"
set-option -ga terminal-overrides ",xterm-256color:Tc"


#List of Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'odedlaz/tmux-onedark-theme'
set -g @tmux-onedark-theme-show-powerline true
set -g @tmux-onedark-theme-show-flags true 
set -g @tmux-onedark-theme-show-left-icon session
set -g status-position top


#Stay at bottom
run '~/.config/tmux/plugins/tpm/tpm'
